### PR TITLE
Add multimodal isocrhone support.

### PR DESCRIPTION
**Pull request by dnesbitt61**
Create a couple of common methods to simplify code a bit.

### CODE REVIEW

**Comment by kevinkreiser** [comment]
i dont understand the benefit to `Initialize` vs having this code in the constructor. i think it makes the interface confusing by presenting an option you dont want a person to actually be able to call multiple times, or do you want that?

**Comment by dnesbitt61** [comment]
Initialize is called every time Compute (or ComputeMultiModal) - it clears the prior temporary information (edge labels, edge status, etc.). We can discuss how to properly use this within the service. But don't want the constructor to reserve the temporary data - only when it is initially used should it reserve memory.

**Comment by kevinkreiser** [comment]
you can still remove the initialize method and get that effect. in fact, a better way migth be to remove the clear and function as well, put this back into the constructor and use a shared_ptr in the service.

**Comment by kevinkreiser** [comment]
im just for simpler less java-y interfaces :wink:

**Comment by kevinkreiser** [comment]
:rocket:

**Pull request merged**
