### PR TITLE
date time fix

### PR DESCRIPTION
**Pull request by gknisely**
date time is now set on the origin in set_origin if we are starting at the current time.

### CODE REVIEW

**Comment by kevinkreiser** [comment]
is there a reason to do that common code in `set_origin` in both of the different path finding algorithms instead of once in, for example, the service before it calls either of them? just wonder if we can remove duplication by doing it further up stream

**Comment by kevinkreiser** [comment]
other than comment looks good to me!

**Comment by gknisely** [comment]
I am fine with that, but I don't want to do that now.  I will do it when we set the default to current if no type is set by the user.  Sound good?  Also, I checked in an arrive by fix.  Please review.

**Comment by kevinkreiser** [comment]
looks good to me

**Pull request merged**
